apiVersion: skaffold/v2beta26
kind: Config
profiles:
  - name: test
    deploy:
      helm:
        releases:
          - name: nault
            namespace: test
            chartPath: ./helm-charts/nault
            valuesFiles:
              - helm-charts/nault/values.yaml
            setValues:
              nault.abbreviation: test
              nault.live.ingress.host: test-wallet.verigasvc.com

          - name: ninja
            namespace: test
            chartPath: ./helm-charts/ninja
            valuesFiles:
              - helm-charts/ninja/values.yaml
            setValues:
              ninja.abbreviation: test
              ninja.live.ingress.host: test-ninja.verigasvc.com

          - name: node
            namespace: test
            chartPath: ./helm-charts/node
            valuesFiles:
              - helm-charts/node/values.yaml
            setValues:
              nano-node.abbreviation: test
              nano-node.live.peering.enabeled: true
              nano-node.live.peering.port: 7180

          - name: proxy
            namespace: test
            chartPath: ./helm-charts/proxy
            valuesFiles:
              - helm-charts/proxy/values.yaml
            setValues:
              proxy.abbreviation: test
              proxy.live.rpc.ingress.host: test-rpc.verigasvc.com
              proxy.live.webSocket.ingress.host: test-ws.verigasvc.com
              proxy.live.nodeURL: http://rpc-live:7076
              proxy.live.nodeWSURL: http://ws-live:7078
              proxy.live.useBPOW: true

          # do not delete or uninstall this release
          # if you must; make sure data is backed before delete
          - name: pv
            namespace: test
            chartPath: ./helm-charts/pv
            valuesFiles:
              - helm-charts/proxy/values.yaml
            setValues:
              pv.abbreviation: test

          - name: rpc
            namespace: test
            chartPath: ./helm-charts/rpc
            valuesFiles:
              - helm-charts/rpc/values.yaml
            setValues:
              nano-node.abbreviation: test
              nano-node.live.peering.enabled: false
              nano-node.live.rpc.enabled: true
              nano-node.live.webSocket.enabled: true

  - name: tst0
    deploy:
      helm:
        releases:
          # do not delete or uninstall this release
          # if you must; make sure data is backed before delete
          - name: pv
            namespace: tst0
            chartPath: ./helm-charts/pv
            valuesFiles:
              - helm-charts/proxy/values.yaml
            setValues:
              pv.abbreviation: tst0

          - name: mosquitto
            namespace: tst0
            chartPath: ./helm-charts/mosquitto
            valuesFiles:
              - helm-charts/mosquitto/values.yaml
            setValues:
              mosquitto.abbreviation: tst0
              mosquitto.live.ingress.host: tst0-bpow.verigasvc.com

          - name: redis
            namespace: tst0
            chartPath: ./helm-charts/redis
            valuesFiles:
              - helm-charts/redis/values.yaml

          - name: nault
            namespace: tst0
            chartPath: ./helm-charts/nault
            valuesFiles:
              - helm-charts/nault/values.yaml
            setValues:
              nault.abbreviation: tst0
              nault.live.ingress.host: tst0-wallet.verigasvc.com

          - name: ninja
            namespace: tst0
            chartPath: ./helm-charts/ninja
            valuesFiles:
              - helm-charts/ninja/values.yaml
            setValues:
              ninja.abbreviation: tst0
              ninja.live.ingress.host: tst0-ninja.verigasvc.com
              #ninja.live.ninja.DRPCResponseLine: '\[\"https:\/\/tst0-rpc1.verigasvc.com\/proxy\", \"https:\/\/tst0-rpc2.verigasvc.com\/proxy\"\]'
              ninja.live.ninja.DRPCResponseLine: '[]'

          - name: node
            chartPath: ./helm-charts/node
            namespace: tst0
            setValues:
              nano-node.abbreviation: tst0
              nano-node.live.node.enabled: "true"
              nano-node.live.peering.enabled: "true"
              nano-node.live.peering.port: "7181"
              nano-node.live.rpc.enabled: "false"
              nano-node.serviceAccount.create: "false"
              nano-node.cloudflareZoneName: "verigasvc.com"

          - name: proxy-0
            namespace: tst0
            chartPath: ./helm-charts/proxy
            valuesFiles:
              - helm-charts/proxy/values.yaml
            setValues:
              proxy.abbreviation: tst0
              proxy.live.rpc.ingress.host: tst0-rpc1.verigasvc.com
              proxy.live.webSocket.ingress.host: tst0-ws1.verigasvc.com
              proxy.live.nodeURL: rpc-live-0.rpc-live
              proxy.live.nodeWSURL: rpc-live-0.rpc-live
              proxy.live.useBPOW.enabled: true
              proxy.live.useBPOW.bpowUser: "tst0-rpc"
              proxy.live.useBPOW.bpowKey: "G3wdxUnhT3KVKtSbQ923WfyT"

          - name: proxy-1
            namespace: tst0
            chartPath: ./helm-charts/proxy
            valuesFiles:
              - helm-charts/proxy/values.yaml
            setValues:
              proxy.abbreviation: tst0
              proxy.live.rpc.ingress.host: tst0-rpc2.verigasvc.com
              proxy.live.webSocket.ingress.host: tst0-ws2.verigasvc.com
              proxy.live.nodeURL: rpc-live-1.rpc-live
              proxy.live.nodeWSURL: rpc-live-1.rpc-live
              proxy.live.useBPOW.enabled: true
              proxy.live.useBPOW.bpowUser: "tst0-rpc"
              proxy.live.useBPOW.bpowKey: "G3wdxUnhT3KVKtSbQ923WfyT"

          - name: rpc
            chartPath: ./helm-charts/node
            namespace: tst0
            createNamespace: false
            setValues:
              nano-node.abbreviation: tst0
              nano-node.live.node.enabled: "false"
              nano-node.live.rpc.enabled: "true"
              nano-node.live.peering.enabled: "true"
              nano-node.live.peering.port: "7181"
              nano-node.live.rpc.control: "false"
              nano-node.live.rpc.port: "7076"
              nano-node.live.webSocket.enabled: "true"
              nano-node.live.webSocket.port: "7078"
              nano-node.serviceAccount.create: "false"
              nano-node.cloudflareZoneName: "verigasvc.com"

          - name: bpow
            namespace: tst0
            chartPath: ./helm-charts/bpow
            valuesFiles:
              - helm-charts/bpow/values.yaml
            setValues:
              bpow.abbreviation: tst0
              bpow.live.ingress.host: tst0-bpow.verigasvc.com
              bpow.live.mosquitto.passwd: axD74aGd5UKDiJa5QPP3mRXB

  - name: tst1
    deploy:
      helm:
        releases:
          # do not delete or uninstall this release
          # if you must; make sure data is backed before delete
          - name: pv
            namespace: tst1
            chartPath: ./helm-charts/pv
            valuesFiles:
              - helm-charts/proxy/values.yaml
            setValues:
              pv.abbreviation: tst1

          - name: mosquitto
            namespace: tst1
            chartPath: ./helm-charts/mosquitto
            valuesFiles:
              - helm-charts/mosquitto/values.yaml
            setValues:
              mosquitto.abbreviation: tst1
              mosquitto.live.ingress.host: tst1-bpow.verigasvc.com

          - name: redis
            namespace: tst1
            chartPath: ./helm-charts/redis
            valuesFiles:
              - helm-charts/redis/values.yaml

          - name: nault
            namespace: tst1
            chartPath: ./helm-charts/nault
            valuesFiles:
              - helm-charts/nault/values.yaml
            setValues:
              nault.abbreviation: tst1
              nault.live.ingress.host: tst1-wallet.verigasvc.com

          - name: ninja
            namespace: tst1
            chartPath: ./helm-charts/ninja
            valuesFiles:
              - helm-charts/ninja/values.yaml
            setValues:
              ninja.abbreviation: tst1
              ninja.live.ingress.host: tst1-ninja.verigasvc.com
              #ninja.live.ninja.DRPCResponseLine: '\[\"https:\/\/tst0-rpc1.verigasvc.com\/proxy\", \"https:\/\/tst0-rpc2.verigasvc.com\/proxy\"\]'
              ninja.live.ninja.DRPCResponseLine: '[]'

          - name: node
            chartPath: ./helm-charts/node
            namespace: tst1
            setValues:
              nano-node.abbreviation: tst1
              nano-node.live.node.enabled: "true"
              nano-node.live.peering.enabled: "true"
              nano-node.live.peering.port: "7182"
              nano-node.live.rpc.enabled: "false"
              nano-node.serviceAccount.create: "false"
              nano-node.cloudflareZoneName: "verigasvc.com"

          - name: proxy-0
            namespace: tst1
            chartPath: ./helm-charts/proxy
            valuesFiles:
              - helm-charts/proxy/values.yaml
            setValues:
              proxy.abbreviation: tst1
              proxy.live.rpc.ingress.host: tst1-rpc1.verigasvc.com
              proxy.live.webSocket.ingress.host: tst1-ws1.verigasvc.com
              proxy.live.nodeURL: rpc-live-0.rpc-live
              proxy.live.nodeWSURL: rpc-live-0.rpc-live
              proxy.live.useBPOW.enabled: true
              proxy.live.useBPOW.bpowUser: "tst1-rpc"
              proxy.live.useBPOW.bpowKey: "G3wdxUnhT3KVKtSbQ923WfyT"

          - name: proxy-1
            namespace: tst1
            chartPath: ./helm-charts/proxy
            valuesFiles:
              - helm-charts/proxy/values.yaml
            setValues:
              proxy.abbreviation: tst1
              proxy.live.rpc.ingress.host: tst1-rpc2.verigasvc.com
              proxy.live.webSocket.ingress.host: tst1-ws2.verigasvc.com
              proxy.live.nodeURL: rpc-live-1.rpc-live
              proxy.live.nodeWSURL: rpc-live-1.rpc-live
              proxy.live.useBPOW.enabled: true
              proxy.live.useBPOW.bpowUser: "tst1-rpc"
              proxy.live.useBPOW.bpowKey: "G3wdxUnhT3KVKtSbQ923WfyT"

          - name: rpc
            chartPath: ./helm-charts/node
            namespace: tst1
            createNamespace: false
            setValues:
              nano-node.abbreviation: tst1
              nano-node.live.node.enabled: "false"
              nano-node.live.rpc.enabled: "true"
              nano-node.live.peering.enabled: "true"
              nano-node.live.peering.port: "7182"
              nano-node.live.rpc.control: "false"
              nano-node.live.rpc.port: "7076"
              nano-node.live.rpc.enable_voting: "false"
              nano-node.live.webSocket.enabled: "true"
              nano-node.live.webSocket.port: "7078"
              nano-node.serviceAccount.create: "false"
              nano-node.cloudflareZoneName: "verigasvc.com"

          - name: bpow
            namespace: tst1
            chartPath: ./helm-charts/bpow
            valuesFiles:
              - helm-charts/bpow/values.yaml
            setValues:
              bpow.abbreviation: tst1
              bpow.live.ingress.host: tst1-bpow.verigasvc.com
              bpow.live.mosquitto.passwd: axD74aGd5UKDiJa5QPP3mRXB
