proxy:
  live:
    enabled: true
    image:
      tag: proxy-V22.1
    logLevel: "info"
    nodeURL: "http://rpc-live:7076"
    nodeWSURL: "ws://ws-live:7078"
    replicaCount: 1
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    rpc:
      ingress:
        enabled: true
        host:
    webSocket:
      ingress:
        enabled: true
        host:
