apiVersion: v2
appVersion: V22.1
description: Helm chart for MyNanoNinja
name: rpc
version: 22.1.0
type: application

dependencies:
  - name: nano-node
    version: 22.1.0
    repository: https://charts.veriga.net
